Pancaim 9 json export functionality
thehyve/PANCAIM-CDM pull request #3
Opened 2023-03-07 16:21 UTC by herl91

Solves [PANCAIM-9](https://thehyve.atlassian.net/jira/software/c/projects/PANCAIM/boards/124?modal=detail&selectedIssue=PANCAIM-9).

Includes pytests for uploading dummy data (in resources/test_data) and comparing the exported json files with provided prebuilt json.

pytest database is handled by pytest-posgresql, no docker at all.

Includes max_slots functionality: the sql statement will limit to the number of max slots per table. The test data for the surgery table does have more items for pancaim_id=123 (4) than max+slots (3).

[PANCAIM-9]: https://thehyve.atlassian.net/browse/PANCAIM-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-13 15:45 UTC, alepev commented on src/pancaim_cdm/export/export.py
> +    )
this code can be moved to the PANCAIM ETL in a parallel PR. it can be integrated into `main.py` or added to a separate script (in principle the ETL will execute transformation-data validation-export with a single trigger action script, so the first option is suitable)

2023-03-13 15:49 UTC, alepev commented on tests/export/test_export_format.py
> +@pytest.fixture()
```suggestion
@pytest.fixture(scope="module")
```

2023-03-13 16:03 UTC, alepev commented on src/pancaim_cdm/export/export_models.py
> +    export_folder: DirectoryPath
Actually I just realized that we don't really need the flexibility of a separate export config. Since the ETL is dockerized, we can use a fixed (hard-coded) export location inside the container, and instead make the local path (outside the container) that is mapped to that location configurable through a Docker ENV variable. In the PANCAIM ETL, you can extract the database info and cdm schema from the general config and pass it to the export function.

2023-03-13 16:07 UTC, alepev commented on src/pancaim_cdm/export/write.py
> +    raise TypeError("Type %s not serializable" % type(obj))
nice, I didn't know of the `default` option in json.dump!

2023-03-13 16:47 UTC, alepev commented on src/pancaim_cdm/export/export_models.py
> +    export_folder: DirectoryPath
I think best to make this a separate Jira ticket in case, the focus of this PR is different. if the export works fine, it can be refactored later where the export folder is being configured.

2023-03-13 16:50 UTC, alepev commented on tests/conftest.py
> +@pytest.fixture()
this and following fixtures too, if the result doesn't need to change between tests, best to set as "session" level.

2023-03-13 17:11 UTC, alepev commented on tests/conftest.py
> +    return files
I would add something like this to the module where you need that specific test data, and explicitly load file X to table X (without using the if).

2023-03-13 17:15 UTC, alepev commented on tests/conftest.py
> +    return files
or make it more generic: always load "tablename.csv" (if present) to table "Tablename". you could use a dictionary where specific names and mapped to specific tables. enforcing one filename spelling (lowercase for example) is better in this case, no need to give so much flexibility. 
(probably this options is better, given that other fixtures depend on it)

2023-03-13 17:16 UTC, alepev commented on tests/conftest.py
> +        return cdm.Tumor(**d)
here also, better to use a dictionary and extract the target table with get. it could be the same dictionary used in the previous fixture.

2023-03-13 18:03 UTC, alepev commented on tests/conftest.py
> +        yield sessionmaker(bind=engine, expire_on_commit=False)
I had a look at this `postgresql` fixture and I find it interesting but also a bit inconvenient for some things.
- `postgresql` seems to be function-level, than means a new database needs to be created and prepared for every test making use of it. now that there is only one test is doesn't matter, but as soon as we add more it will, in terms of efficiency. it would be better to have a single session-level database setup fixture, to be shared between all tests, and a function-level fixture based on it to drop and reload the (test-specific) data.
- thinking of automated testing once we set up tests to be triggered by a GitHub action, we might need the `postgresql_noproc` instead of `postgres` fixture (found this in the docs). that would allow us to specify a connection to the Docker database created by the GitHub action.
- I guess the `postgres` fixture is popping up a database using any postgres installation if finds on the host system? this could be a problem because it makes the test setup details very implicit. since we are running the ETL on a postgres 14 docker container, I would like to make sure that this fixture also runs the tests on a postgres 14 database (and not another unspecified version).

2023-03-13 18:05 UTC, alepev commented on tests/conftest.py
> +        yield sessionmaker(bind=engine, expire_on_commit=False)
I suggest: either let's setup this to work with `postgresql_noproc`, so that it can be automated and the postgres version is explicit, or switch back to a Docker setup. In the latter case, it would be preferable to create a new ticket since the goal is different (i.e. export functionality vs improving test setup).

2023-03-13 18:07 UTC, alepev commented on tests/export/test_export_format.py
> +    export_config = ExportConfig(**default_export_config)
these operations would be better in a fixture (if we add any other export tests)

2023-03-13 18:09 UTC, alepev commented on tests/export/test_export_format.py
> +    export_folder = max(export_folder, key=os.path.getctime)                                                                    # this is the latest dir in the export_dir
uuuuh I would rather just setup the tests so that there is only one folder

2023-03-13 18:11 UTC, alepev reviewed
Good job with the export functionality. Most of the remarks I have are on the test setup, but it's something that probably makes more sense to address in a new Jira ticket as to not completely swamp this PR.

2023-03-14 09:32 UTC, herl91 commented on src/pancaim_cdm/export/export.py
> +    )
Should I add a jira ticket to the ETL side to eventually do that transfer?

2023-03-14 09:40 UTC, herl91 commented on tests/conftest.py
> +            records.append(create_record(cur_table, cur_record))
Yes, you are correct. I think the idea was that this way "create_record" can be used in other tests that where data that does not come from CSVs.

So load_synth_data_to_cdm handles reading the CSV into dicts, and create_record handles dict into CDM objects.

2023-03-14 09:52 UTC, herl91 commented on tests/conftest.py
> +    return files
I think I like the former option better. Make the filenames more explicit too, have them only be loaded by the test that it's gonna use them and avoid having to modify this code whenever new tests are added that involve new CSVs.

2023-03-14 10:07 UTC, herl91 commented on tests/export/test_export_format.py
> +    export_folder = max(export_folder, key=os.path.getctime)                                                                    # this is the latest dir in the export_dir
Fair, but I was unsure on how to achieve that. Even though the export_folder creating is handled by the test, the subfolder creating (that has the timestring name) is handled by the ExportWriter, which is itself what we are testing. The only solution that occurs to me, is to add a new bool param to "export_cdm_tables" like "test", so that if it's true, the subfolder name will be a specific string, rather than the timestring.

It's a decent solution, but it seems rather odd to test a function in this pytest setup when that function itself has a "test" param that will change how the function will behave if it's a test. Granted, a string name is a very small and irrelevant matter, but it seems to me like it goes against the... purpose of it all. Like a surprise quiz that is announced the day before.

Do you have another solution or should I implement that?

2023-03-14 10:36 UTC, herl91 commented on tests/conftest.py
> +        yield sessionmaker(bind=engine, expire_on_commit=False)
I'm not fully sure, but I think it's not only function-level. At least [this part](https://pypi.org/project/pytest-postgresql/#:~:text=Using%20a%20common%20database%20initialisation%20between%20tests) here seems to suggest you can set up one database for multiple tests.

About `postgresql_noproc`, you're right.

About the third point, I think you can control the version and psql installation used by the test. In particular, I think using the `DatabaseJanitor` one can control the psql version, and also manage the db in between tests, which I think it's cryptically explained [here](https://pypi.org/project/pytest-postgresql/#:~:text=Maintaining%20database%20state%20outside%20of%20the%20fixtures), and more illustratively shown [here](https://github.com/pypi/warehouse/blob/5d15bfe/tests/conftest.py#L127).

So yeah, you are right, I guess there's two options:
1) Add the `DatabaseJanitor`, probably with `postgresql_noproc` within this PR so that this can be used in following tests.
2) Add a new Jira issue to "Dockerize" the testing with the previous setup, so that docker-db can be used in following tests.

I'm ok with either. At the time I found it simpler to use this fixture than to set up docker, but I now have set up docker when testing the other PR. Everything is going to be docker anyway, so perhaps the second option keeps everything more in-sync, so I'm leaning towards the second even though I'm the one that brought the first option haha. I'll let you decide!

2023-03-14 10:46 UTC, herl91 commented on tests/conftest.py
> +@pytest.fixture()
I think I subconciously ignored scoping anything since there's just the one test. But yeah, added scopes now.

2023-03-14 11:06 UTC, herl91 commented on src/pancaim_cdm/export/export_models.py
> +    export_folder: DirectoryPath
you are right, but I think the best solution is probably a mix of the two: just hardcode a `default_export_config`, similar to the one used by the test. Yes, it is unused/waste flexibility, but it barely bloats, requires the least amount of work, and allows us to more easily change stuff in the future, say, if CM decides they do want some basic export options, like how slots are filtered/ordered or whatever.

2023-03-16 10:03 UTC, herl91 commented on tests/conftest.py
> +        yield sessionmaker(bind=engine, expire_on_commit=False)
I've added a new JIRA ticker to dockerize the pytest.

2023-03-16 10:05 UTC, herl91 commented on src/pancaim_cdm/export/export_models.py
> +    export_folder: DirectoryPath
It's already an issue: PANCAIM-25

2023-03-16 10:08 UTC, herl91 commented on src/pancaim_cdm/export/export.py
> +    )
Actually, I think this can be combined with PANCAIM-25 (the export config). Thoughts?

2023-03-17 14:33 UTC, alepev commented on src/pancaim_cdm/export/export.py
> +    )
Mmm it's a bit different.. This is about adding the export functionality to the ETL, and PANCAIM-25 is a refactoring to remove the need for a configuration file (to do things properly, I should have added a matching ticket for both PANCAIM-9 and PANCAIM-25 in the other repository.. I will create them). Generally speaking, we tend to split issues into smaller chunks whenever possible to keep them manageable and easy to review, so it's not a bad thing to have separate ones (unless they are clearly duplicates of course!)

2023-03-17 14:39 UTC, alepev commented on src/pancaim_cdm/export/export.py
> +    )
OK I added the missing issues, so now there are pairs of related issues:
- PANCAIM 9 (CDM) & 31 (ETL) -> export code
- PANCAIM 30 (CDM) & 25 (ETL) -> export location / config refactoring

2023-03-20 10:14 UTC, herl91 commented
Ready for re-review @Spayralbe

2023-04-04 18:51 UTC, Spayralbe requested changes
@herl91 As we discussed, I've only looked at the export code and not the tests as they will be rewritten as part of a separate PR.

I've added some suggestions/questions in the comments.

An issue I encountered when adding some numeric data (e.g. a weight value in the body_measurement table) is that these currently crash upon export. This happens because SQLAlchemy returns numeric values from the DB as python `Decimal` objects and the json.dump function doesn't know what to do with these. Please make sure these values are converted to floats so they can be exported.

2023-04-04 18:51 UTC, Spayralbe commented on src/pancaim_cdm/export/export.py
> +        export_schema=cdm.CDM_SCHEMA,
```suggestion
        export_schema=config.cdm_schema,
```
Otherwise the schema placeholder "cdm_schema" is used

2023-04-04 18:51 UTC, Spayralbe commented on src/pancaim_cdm/export/write.py
> +        conn.close()
Is already closed automatically as soon as the `with` block ends
```suggestion
```

2023-04-05 09:49 UTC, herl91 commented on src/pancaim_cdm/export/constants.py
> +}
The first 2 I dont remember anymore, as for the latter 2, they were initially meant to be part of the export, but CM eventually said to export everything and not sort things, so these will be used in data validation.

Will remove from this branch.

2023-04-05 09:55 UTC, herl91 commented on src/pancaim_cdm/export/write.py
> +        person_table = db.get_reflected_metadata(export_schema).tables[f'{export_schema}.{Person.__tablename__}']           # is there a better way to refer to person table name?
The comment-question was about a way to avoid "Person.__tablename__", but alas, seems like there is no better way.

Will commit your suggestions.

2023-04-05 10:13 UTC, herl91 commented
@Spayralbe Added all changes you suggested, and a fix for the Decimal issue (after I re-requested the re-re-review, so make sure you check the latest commit)

2023-04-05 12:14 UTC, Spayralbe reviewed
One tiny thing remaining, otherwise all good!

2023-04-05 12:23 UTC, merged